export const availableFor = [
  `Full-time Job`,
  `Part-time Job`,
  `Freelance Work`,
  `Investing in Startups`,
  `Co-founding a Startup`,
  `Advising Companies`,
  `Building an MVP`,
  `Designing a Product`,
  `Managing a Product`,
  `Participating in User Research`,
  `Mentoring`,
  `Giving resume feedback`,
  `Reviewing portfolios`,
  `Beta testing new products`,
  `Coffee Chat`,
  `Virtual Meetup`,
  `Working on side projects`,
  `Giving Adivce`,
  `Recruiting Talents`,
  `Interviewing Talents`,
  `Starting a Nonprofit`,
  `Sponsoring Events`,
  `Speaking at Events`,
  `Internship`,
  `Joining a Board`,
  `Volunteer Work`,
  `Pitching Ideas`,
  `Building a Community`,
  `Managing a Community`,
  `Organizing a Hackathon`,
  `Open-source Contributions`,
  `Competitive Programming`,
  `Attending Hackathons`,
  `Attending Developer Events`,
  `Participating in Career Fairs`,
  ` Getting Resume Feedback`,
  `Getting My Portfolio Reviewed`,
  `Building Products that Scale`,
  `Forming a DAO`,
  `Trying a Product`,
  `Interview or AMA`,
  `Philanthropy`,
  `Donating to Nonprofits`
];
