export const describes = [
  `Advsior`,
  `Angel Investor`,
  `Back-end Developer`,
  `Big Data Developer`,
  `Blockchain Developer`,
  `Board Member`,
  `CRM Developer`,
  `Cloud Architect`,
  `Cloud Computing Developer`,
  `Computer Scientist`,
  `Data Engineer`,
  `Data Scientist`,
  `Database Adminstrator`,
  `Desktop Developer`,
  `DevOps Engineer`,
  `Developer Advocate`,
  `Developer Evangelist`,
  `Developer Marketer`,
  `Developer Relations`,
  `Embedded Developer`,
  `Founder`,
  `Front-end Developer`,
  `Full-stack Developer`,
  `Game Developer`,
  `Hackathon Evangelist`,
  `Hackathon Organizer`,
  `Hacker`,
  `Hiring Manager`,
  `Machine Learning Engineer`,
  `Maker`,
  `Mentor`,
  `Mobile Developer`,
  `Network Engineer`,
  `No-code Developer`,
  `Open Source Advocate`,
  `Open Source Contributor`,
  `Product Design`,
  `Product Manager`,
  `Recruiter`,
  `Robotics Developer`,
  `Security Engineer`,
  `Software Engineer`,
  `Speaker`,
  `Talent Acquisition`,
  `Talent Acquisition`,
  `Technical Recruiter`,
  `UI/UX Designer`,
  `Venture Capitalist`,
  `Web Developer`
] as const;
